export const ERROR_CODES = Object.freeze({
  // OTP
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_TOO_MANY_REQUESTS: 'OTP_TOO_MANY_REQUESTS',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_RESEND_LIMIT: 'OTP_RESEND_LIMIT',

  // Auth
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_SIGNUP_TOKEN_INVALID: 'AUTH_SIGNUP_TOKEN_INVALID',

  // Account
  ACCOUNT_DUPLICATE_NAME: 'ACCOUNT_DUPLICATE_NAME',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_TYPE_DISABLED: 'ACCOUNT_TYPE_DISABLED',
  ACCOUNT_FORBIDDEN: 'ACCOUNT_FORBIDDEN',
  ACCOUNT_PERSONAL_EXISTS: 'ACCOUNT_PERSONAL_EXISTS',
  ACCOUNT_PERSONAL_UNDELETABLE: 'ACCOUNT_PERSONAL_UNDELETABLE',

  // User
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Follower
  FOLLOWER_ALREADY_EXISTS: 'FOLLOWER_ALREADY_EXISTS',
  FOLLOWER_NOT_FOUND: 'FOLLOWER_NOT_FOUND',
  FOLLOWER_SELF_FOLLOW: 'FOLLOWER_SELF_FOLLOW',
  FOLLOWER_ACCOUNT_NOT_PUBLIC: 'FOLLOWER_ACCOUNT_NOT_PUBLIC',
  FOLLOWER_ACCOUNT_NOT_ALLOWED: 'FOLLOWER_ACCOUNT_NOT_ALLOWED',

  // General
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMIT: 'RATE_LIMIT',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
});
